#服务端口号
server:
  port: 20000

spring:
  #服务名
  application:
    name: sunerp-wecom-gateway
  main:
    #gateway使用的是webflux,需要跟web-mvc区别开
    web-application-type: reactive
    #允许同名的bean覆盖注入
    allow-bean-definition-overriding: true
  #http最大输入大小
  http:
    max-buffered-input-size: 1048576
  #nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: false
      #路由跳转策略
      routes:
        - id: workflow-todo
          uri: lb://sunerp-wecom
          predicates:
            - Path=/workflow/taskPlus/query/userTask #路径匹配
          filters:
            - StripPrefix=1
        - id: workflow
          uri: lb://workflow
          predicates:
            - Path=/workflow/** #路径匹配
          filters:
            - StripPrefix=1
        - id: sunerp-wecom
          uri: lb://sunerp-wecom
          predicates:
            - Path=/wecom/** #路径匹配
          filters:
            - StripPrefix=1
        - id: ee
          uri: lb://sunerp-web
          predicates:
            - Path=/ee/** #路径匹配
          filters:
            - StripPrefix=1
        - id: pcmc-plus-server
          uri: lb://pcmc-plus-server
          predicates:
            - Path=/pcmc-plus-server/** #路径匹配
          filters:
            - StripPrefix=1
        - id: pcmc-service
          uri: lb://pcmc-service
          predicates:
            - Path=/pcmc-service/** #路径匹配
          filters:
            - StripPrefix=1
  #==============redis配置==============
  redis:
    host: 127.0.0.1
    database: 0
    port: 32309
    timeout: 10000          # 连接超时时间，单位ms
    lettuce:
      pool:
        max-active: 10         # 连接池最大连接数（使用负值表示没有限制） 默认 10
        max-wait: -1          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1，单位ms
        max-idle: 8           # 连接池中的最大空闲连接 默认 8
        min-idle: 0           # 连接池中的最小空闲连接 默认 0

#日志级别
logging:
  level:
    org.springframework: DEBUG
#    com.sunline.erp: DEBUG